tmp-prod-full/objects/ApexAuditTrail__c/ApexAuditTrail__c.object-meta.xml
<CustomObject>
    <description>Apex 실행과 관련된 주요 이벤트 및 트랜잭션의 상세 기록을 제공하여 Salesforce 환경에서 모니터링 할 수 있도록 지원</description>
    <label>로그 관리</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

tmp-prod-full/objects/ApexAuditTrail__c/fields/ApexClass__c.field-meta.xml
<CustomField>
    <fullName>ApexClass__c</fullName>
    <description>실행 된 Apex 클래스 명</description>
    <label>ApexClass</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

tmp-prod-full/objects/ApexAuditTrail__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

tmp-prod-full/objects/ApexAuditTrail__c/fields/ErrorCode__c.field-meta.xml
<CustomField>
    <fullName>ErrorCode__c</fullName>
    <description>발생한 오류의 코드</description>
    <label>ErrorCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

tmp-prod-full/objects/ApexAuditTrail__c/fields/ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>ErrorMessage__c</fullName>
    <description>발생한 오류의 설명 메시지</description>
    <label>ErrorMessage</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

tmp-dev-full/objects/ApexAuditTrail__c/fields/FailedRecordIds__c.field-meta.xml
<CustomField>
    <fullName>FailedRecordIds__c</fullName>
    <description>처리 실패한 레코드 Id 목록 ( 세미콜론(;) 으로 구분 )</description>
    <label>FailedRecordIds</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

tmp-dev-full/objects/ApexAuditTrail__c/fields/HttpStatusCode__c.field-meta.xml
<CustomField>
    <fullName>HttpStatusCode__c</fullName>
    <description>인터페이스 호출 후 반환 된 HTTP 상태 코드</description>
    <label>HttpStatusCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

tmp-dev-full/objects/ApexAuditTrail__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

tmp-dev-full/objects/ApexAuditTrail__c/fields/RequestBody__c.field-meta.xml
<CustomField>
    <fullName>RequestBody__c</fullName>
    <description>인터페이스 호출 시 전송 된 요청 본문</description>
    <label>RequestBody</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

tmp-dev-full/objects/ApexAuditTrail__c/fields/RequestDateTime__c.field-meta.xml
<CustomField>
    <fullName>RequestDateTime__c</fullName>
    <description>요청이 전송 된 날짜 및 시간</description>
    <label>RequestDateTime</label>
    <type>DateTime</type>
</CustomField>

tmp-prod-full/objects/ApexAuditTrail__c/fields/RequestUrl__c.field-meta.xml
<CustomField>
    <fullName>RequestUrl__c</fullName>
    <description>인터페이스 호출에 사용된 요청 URL ( GET 방식의 경우 Query Parameter 포함 )</description>
    <label>RequestUrl</label>
    <type>Url</type>
</CustomField>

tmp-prod-full/objects/ApexAuditTrail__c/fields/ResponseBody__c.field-meta.xml
<CustomField>
    <fullName>ResponseBody__c</fullName>
    <description>인터페이스 호출의 응답 본문</description>
    <label>ResponseBody</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

tmp-prod-full/objects/ApexAuditTrail__c/fields/ResponseDateTime__c.field-meta.xml
<CustomField>
    <fullName>ResponseDateTime__c</fullName>
    <description>인터페이스 응답이 수신된 날짜 및 시간</description>
    <label>ResponseDateTime</label>
    <type>DateTime</type>
</CustomField>

tmp-prod-full/objects/ApexAuditTrail__c/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <description>오류 발생 시의 호출 스택 ( 디버깅 용도 )</description>
    <label>StackTrace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

tmp-prod-full/objects/ApexAuditTrail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Apex 실행 상태
- SUCCESS : 성공
- ERROR : 오류 발생으로 인한 실패
- PARTIAL : 부분 성공</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>PARTIAL</fullName>
            </value>
            <value>
                <fullName>SUCCESS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ErrorLogUIControllerV1.cls
public with sharing class ErrorLogUIControllerV1 {

    @AuraEnabled(cacheable=true)
    public static ApexAuditTrail__c getDetail(Id recordId) {
        return [
            SELECT
                Name,
                Status__c,
                ErrorCode__c,
                ErrorMessage__c,
                HttpStatusCode__c,
                RequestDateTime__c,
                ResponseDateTime__c,
                ApexClass__c,
                Method__c,
                RequestUrl__c,
                RequestBody__c,
                ResponseBody__c,
                StackTrace__c,
                Description__c,
                FailedRecordIds__c
            FROM ApexAuditTrail__c
            WHERE Id = :recordId
            LIMIT 1
        ];
    }
}